// Romance Unplugged - product catalog (cloned from app.intimacy.school)
export type CatalogProduct = {
  slug: string;
  cover: string;
  title: string;
  shortTitle: string;
  h1: string;
  emoji: string;
  category: string;
  tagline: string;
  heroSub: string;
  props: string[];
  rating: string;
  reviewLabel: string;
  pagesLabel: string;
  badge: string;
  price: number;
  original: number;
  discount: number;
  couplesLabel: string;
  pains: string[];
  painNote: string;
  story: string;
  benefitTitle: string;
  benefits: { emoji: string; title: string; text: string }[];
  faqs: { q: string; a: string }[];
};

export const PRODUCTS: CatalogProduct[] = [
  {
    slug: "75-positions-that-every-couple-must-try",
  cover: "/covers/75-positions-that-every-couple-must-try.webp",
    title: "75 Positions Every Couple Must Try",
    shortTitle: "75 Positions",
    h1: "75 S❤️‍🔥X Positions Jo Har Couple Ko Zaroor Try Karni Chahiye",
    emoji: "🔥",
    category: "Positions",
    tagline: "A curated bucket list for a spicier love life",
    heroSub: "India's most complete sex position guide — beginner se wild tak. Aaj raat se shuru karo. 🔥",
    props: ["🌶️ Last longer in bed", "💥 Satisfy fully — every time", "🔥 75 hot positions", "😏 Make them beg for more"],
    rating: "4.9",
    reviewLabel: "20,000+ ratings",
    pagesLabel: "115+ Pages",
    badge: "India's Hottest",
    price: 599,
    original: 999,
    discount: 40,
    couplesLabel: "50,000+ couples",
    pains: [
      "Hamesha same position — sex boring ho gaya hai?",
      "Jaldi khatam — partner unsatisfied rehta/rehti hai?",
      "Partner bedroom mein excited hi nahi dikhta/dikhti?",
      "Sex sirf routine ban gaya — koi passion nahi?",
    ],
    painNote: "Agar 2 bhi haan hain — yeh ebook exactly iske liye bani hai.",
    story: "Maine 10,000+ couples se poochha — bedroom mein kitne positions try kiye ho? Average answer: 4. Maximum: 7. Yeh sunke mujhe bilkul hairani nahi hui. Koi honest guide nahi thi — jo clearly bataaye ki yeh 75 positions hain jo actually kaam karti hain. Illustrated. Hindi mein. No shame. Toh maine woh guide banayi. 115+ pages, 75 positions — beginner se wild tak — har ek ke saath clear images aur step-by-step instructions. Jo kaam karta hai woh — koi theory nahi. Aur sach — jo couples yeh try karte hain, unka bedroom life literally change ho jaata hai. 20,000+ reviews kuch toh bol rahe hain.",
    benefitTitle: "75 Positions — 3 Categories",
    benefits: [
      { emoji: "🌱", title: "Beginner", text: "Comfortable, easy-to-follow positions for starting out." },
      { emoji: "🔥", title: "Intermediate", text: "Build intensity and discover what works for both of you." },
      { emoji: "🌶️", title: "Advanced", text: "For couples ready to push boundaries with confidence." },
    ],
    faqs: [
      { q: "Is this available in Hindi?", a: "Yes — the full ebook is bilingual (Hindi + English) with illustrated guides." },
      { q: "How fast is delivery?", a: "Instant — the PDF is delivered to your email right after payment." },
    ],
  },
  {
    slug: "28-secret-tips-for-the-first-night",
  cover: "/covers/28-secret-tips-for-the-first-night.webp",
    title: "28 Secret Tips for the First Night",
    shortTitle: "First Night Tips",
    h1: "28 Secret Tips for the First Night",
    emoji: "🌙",
    category: "First Time",
    tagline: "Pehli raat ko yaadgar banayein",
    heroSub: "Make your first night unforgettable — with confidence and comfort.",
    props: ["🌙 No awkwardness", "💞 Build instant comfort", "🔥 28 proven tips", "😌 Both feel relaxed"],
    rating: "4.5",
    reviewLabel: "3.9k reviews",
    pagesLabel: "60+ Pages",
    badge: "Bestseller",
    price: 599,
    original: 999,
    discount: 40,
    couplesLabel: "100,000+ couples",
    pains: [
      "Nervous about the first night?",
      "Kya karna hai kya nahi — samajh nahi aata?",
      "Partner ko comfortable kaise banayein?",
      "Expectations match nahi karti?",
    ],
    painNote: "Pehli raat sirf ek baar aati hai — ise perfect banao.",
    story: "Har couple ke liye pehli raat ek milestone hoti hai. Lekin zyadaatar log nervous hote hain — kya sahi hai, kya nahi. Maine 28 practical tips likhe hain jo nervousness ko confidence mein badal dete hain.",
    benefitTitle: "What's Inside",
    benefits: [
      { emoji: "💬", title: "Communication first", text: "How to talk about the night without awkwardness." },
      { emoji: "🕯️", title: "Setting the mood", text: "Simple ways to make the evening special." },
      { emoji: "💞", title: "Comfort & consent", text: "Make sure both of you feel safe and excited." },
    ],
    faqs: [
      { q: "Is it for both partners?", a: "Yes — the guide is written for both, with sections for each of you." },
      { q: "Is delivery instant?", a: "Yes, instant PDF delivery to your email." },
    ],
  },
  {
    slug: "28-day-intimacy-diet",
  cover: "/covers/28-day-intimacy-diet.jpg",
    title: "28-Day Diet for a Fulfilling Sex Life",
    shortTitle: "Intimacy Diet",
    h1: "28-Day Diet for a Fulfilling Sex Life",
    emoji: "🥗",
    category: "Wellness",
    tagline: "A 4-week nutrition system for stamina, drive and connection",
    heroSub: "What you eat powers your bedroom. This 4-week plan builds stamina and drive naturally.",
    props: ["🥗 28-day meal plan", "⚡ Natural stamina boost", "❤️ Better drive & mood", "📋 Indian foods"],
    rating: "4.8",
    reviewLabel: "1.5k reviews",
    pagesLabel: "80+ Pages",
    badge: "Top Rated",
    price: 199,
    original: 399,
    discount: 50,
    couplesLabel: "30,000+ couples",
    pains: ["Low energy after work?", "Drive down these days?", "Stamina theek nahi?", "Always tired in the bedroom?"],
    painNote: "Aapki plate aapke passion ko power karti hai — sahi khao, sahi jio.",
    story: "Nutrition sab kuch hai — energy, stamina, drive. Maine Indian diet ke hisaab se 28-din ka plan banaya jo couples ke liye specifically designed hai.",
    benefitTitle: "The 4-Week System",
    benefits: [
      { emoji: "🥗", title: "Week 1-2", text: "Clean up, boost energy with simple swaps." },
      { emoji: "⚡", title: "Week 3", text: "Add stamina foods — Indian kitchen se." },
      { emoji: "❤️", title: "Week 4", text: "Full routine — feel the difference." },
    ],
    faqs: [
      { q: "Are the foods easy to find in India?", a: "Yes — every ingredient is available in Indian markets." },
    ],
  },
  {
    slug: "52-weeks-positions",
  cover: "/covers/52-weeks-positions.webp",
    title: "52 Weeks Positions",
    shortTitle: "52 Positions",
    h1: "52 Weeks Positions",
    emoji: "📅",
    category: "Positions",
    tagline: "Jo aap agle 365 dinon mein try kar sakte hain",
    heroSub: "One new position every week for a full year of discovery.",
    props: ["📅 52 weekly positions", "🔥 Never get bored", "💞 Build deeper connection", "🇮🇳 Hindi + English"],
    rating: "4.5",
    reviewLabel: "3.0k reviews",
    pagesLabel: "90+ Pages",
    badge: "Editor's Choice",
    price: 599,
    original: 999,
    discount: 40,
    couplesLabel: "60,000+ couples",
    pains: ["Same routine boring?", "Try something new — but kya?", "Partner ready but plan nahi?", "Want a year of excitement?"],
    painNote: "Har hafte ek naya position — poora saal naya excitement.",
    story: "365 din, 52 positions — ek complete year of discovery. Har week ka ek naya challenge, ek naya experience.",
    benefitTitle: "A Year of Discovery",
    benefits: [
      { emoji: "📅", title: "Weekly plan", text: "52 positions, one for each week of the year." },
      { emoji: "🔥", title: "Build-up", text: "Positions progress from comfortable to adventurous." },
      { emoji: "💞", title: "Connection", text: "Each position designed for closeness, not just variety." },
    ],
    faqs: [{ q: "How is it different from 75 Positions?", a: "52 Weeks is a weekly plan — 75 Positions is the complete A-Z guide." }],
  },
  {
    slug: "69-bedroom-ideas-for-couples",
  cover: "/covers/69-bedroom-ideas-for-couples.webp",
    title: "69 Bedroom Ideas for Couples",
    shortTitle: "69 Ideas",
    h1: "69 Bedroom Ideas for Couples",
    emoji: "💡",
    category: "Ideas",
    tagline: "Fresh ideas to keep things spicy",
    heroSub: "69 creative ideas to keep your bedroom exciting and connected.",
    props: ["💡 69 fresh ideas", "🔥 Easy to try", "💞 For every comfort level", "🇮🇳 Hindi + English"],
    rating: "4.2",
    reviewLabel: "3.0k reviews",
    pagesLabel: "70+ Pages",
    badge: "Popular",
    price: 399,
    original: 999,
    discount: 60,
    couplesLabel: "45,000+ couples",
    pains: ["Ideas khatam ho gaye?", "Wohi purana routine?", "Kuch naya try karna hai?"],
    painNote: "69 ideas — koi bhi aaj raat try kar sakte ho.",
    story: "Kuch din routine boring lagta hai — ideas ki zaroorat hoti hai. Yeh 69 ideas simple se wild tak hain.",
    benefitTitle: "Ideas for Every Mood",
    benefits: [
      { emoji: "🌙", title: "Date night", text: "Set the scene with playful ideas." },
      { emoji: "🔥", title: "Spice it up", text: "Try something bold tonight." },
      { emoji: "💞", title: "Connection", text: "Slow, intimate moments that matter." },
    ],
    faqs: [{ q: "Are all ideas safe and comfortable?", a: "Yes — every idea includes comfort notes and alternatives." }],
  },
  {
    slug: "7-day-stamina-diet",
  cover: "/covers/7-day-stamina-diet.jpg",
    title: "7-Day Stamina Diet Plan",
    shortTitle: "Stamina Diet",
    h1: "7-Day Stamina Diet Plan",
    emoji: "⚡",
    category: "Wellness",
    tagline: "A simple one-week eating plan to boost energy and drive",
    heroSub: "One week. Simple Indian foods. Noticeably better stamina.",
    props: ["⚡ 7-day plan", "🥗 Simple Indian foods", "📋 Grocery list", "❤️ Quick results"],
    rating: "4.7",
    reviewLabel: "860 reviews",
    pagesLabel: "40+ Pages",
    badge: "Quick Win",
    price: 99,
    original: 299,
    discount: 67,
    couplesLabel: "20,000+ couples",
    pains: ["Quick stamina boost chahiye?", "No time for complex diets?", "Want fast, visible results?"],
    painNote: "Sirf 7 din — simple plan, real difference.",
    story: "Kabhi kabhi aapko sirf ek hafte ka push chahiye hota hai. Yeh plan exactly wohi hai — 7 din, simple foods, real stamina difference.",
    benefitTitle: "Your 7-Day Plan",
    benefits: [
      { emoji: "🥗", title: "Day by day", text: "Every meal planned for you." },
      { emoji: "🛒", title: "Grocery list", text: "Everything available in local markets." },
      { emoji: "⚡", title: "Energy boost", text: "Feel the difference by day 4." },
    ],
    faqs: [{ q: "Is this safe with existing diets?", a: "Yes — it's a simple, balanced Indian diet plan." }],
  },
  {
    slug: "14-day-valentine-calender",
  cover: "/covers/14-day-valentine-calender.webp",
    title: "14 Days Valentine Calendar",
    shortTitle: "Valentine Calendar",
    h1: "14 Days Valentine Calendar",
    emoji: "💝",
    category: "Ideas",
    tagline: "14 days of surprises leading to Valentine's Day",
    heroSub: "14 days of romantic surprises, gifts and moments — countdown to Valentine's.",
    props: ["💝 14 daily surprises", "🎁 Gift ideas", "💌 Love notes", "🔥 Build the anticipation"],
    rating: "4.9",
    reviewLabel: "0 reviews",
    pagesLabel: "30+ Pages",
    badge: "New",
    price: 299,
    original: 699,
    discount: 57,
    couplesLabel: "10,000+ couples",
    pains: ["Valentine's pe kya plan hai?", "Surprises dene hain — ideas nahi?", "Romance chahiye — routine nahi?"],
    painNote: "14 din — har din ek naya surprise.",
    story: "Valentine's Day ek din nahi — poora experience hona chahiye. Yeh calendar har din ka ek naya surprise deta hai.",
    benefitTitle: "The Countdown",
    benefits: [
      { emoji: "💌", title: "Love notes", text: "Words that make them smile every morning." },
      { emoji: "🎁", title: "Gift ideas", text: "Thoughtful, budget-friendly surprises." },
      { emoji: "🔥", title: "Grand finale", text: "Valentine's Day planned to perfection." },
    ],
    faqs: [{ q: "Is it for the whole month?", a: "It's 14 days — perfect for the Valentine's countdown." }],
  },
  {
    slug: "bedroom-boss",
  cover: "/covers/bedroom-boss.webp",
    title: "Bedroom Boss",
    shortTitle: "Bedroom Boss",
    h1: "Bedroom Boss",
    emoji: "👑",
    category: "Mindset",
    tagline: "Command confidence in the bedroom",
    heroSub: "Confidence is the most attractive thing you can wear. Learn to own the room.",
    props: ["👑 Build confidence", "🧠 Mindset shift", "🔥 Be present & dominant", "💞 Attract naturally"],
    rating: "4.1",
    reviewLabel: "3.1k reviews",
    pagesLabel: "55+ Pages",
    badge: "Mens' Choice",
    price: 599,
    original: 999,
    discount: 40,
    couplesLabel: "40,000+ couples",
    pains: ["Confidence nahi hai bedroom mein?", "Overthinking sab kharab kar deti hai?", "Partner ko impress karna hai?"],
    painNote: "Confidence skill hai — seekhi ja sakti hai.",
    story: "Bedroom mein sabse bada factor confidence hai — not technique. Yeh guide mindset ko strong banata hai.",
    benefitTitle: "The Mindset Shift",
    benefits: [
      { emoji: "🧠", title: "Let go of fear", text: "Silence the overthinking voice." },
      { emoji: "👑", title: "Own your presence", text: "Walk in with quiet confidence." },
      { emoji: "💞", title: "Lead naturally", text: "Be the partner they crave." },
    ],
    faqs: [{ q: "Is this about being dominant?", a: "It's about confidence and presence — not force." }],
  },
  {
    slug: "bedroom-communication-101-things-to-say",
  cover: "/covers/bedroom-communication-101-things-to-say.webp",
    title: "Bedroom Communication",
    shortTitle: "101 Things to Say",
    h1: "Bedroom Communication — 101 Things to Say",
    emoji: "💬",
    category: "Communication",
    tagline: "101 things to say — in Hindi + English",
    heroSub: "Words change everything. 101 things to say in Hindi and English.",
    props: ["💬 101 phrases", "🇮🇳 Hindi + English", "🔥 Set the mood", "💞 Deeper connection"],
    rating: "4.0",
    reviewLabel: "3.0k reviews",
    pagesLabel: "45+ Pages",
    badge: "Couples' Pick",
    price: 599,
    original: 999,
    discount: 40,
    couplesLabel: "35,000+ couples",
    pains: ["Kya bolna hai pata nahi?", "Silence awkward lagti hai?", "Mood set karna hai?"],
    painNote: "Sahi words sahi time pe — game changer.",
    story: "Bedroom mein words matter karte hain. Yeh 101 phrases Hindi aur English mein — har mood ke liye.",
    benefitTitle: "Phrases for Every Moment",
    benefits: [
      { emoji: "💬", title: "Foreplay", text: "Words that build anticipation." },
      { emoji: "🔥", title: "In the moment", text: "Say the right thing at the right time." },
      { emoji: "💞", title: "Aftercare", text: "Words that deepen the bond after." },
    ],
    faqs: [{ q: "Is it awkward to read?", a: "No — written to be natural and comfortable." }],
  },
  {
    slug: "oral-mastery",
  cover: "/covers/oral-mastery.webp",
    title: "Oral Mastery",
    shortTitle: "Oral Mastery",
    h1: "Oral Mastery",
    emoji: "👅",
    category: "Technique",
    tagline: "Techniques couples wish they knew sooner",
    heroSub: "Step-by-step techniques for pleasure that couples wish they discovered sooner.",
    props: ["👅 Step-by-step", "🔥 Real techniques", "💞 Partner-focused", "🇮🇳 Hindi + English"],
    rating: "4.8",
    reviewLabel: "3.6k reviews",
    pagesLabel: "65+ Pages",
    badge: "High Rated",
    price: 599,
    original: 999,
    discount: 40,
    couplesLabel: "50,000+ couples",
    pains: ["Techniques theek nahi lagti?", "Partner ko satisfy karna hai?", "Kya sahi hai pata nahi?"],
    painNote: "Right technique = right pleasure.",
    story: "Oral pleasure ek art hai. Yeh guide har step ko clearly explain karta hai — for both partners.",
    benefitTitle: "The Masterclass",
    benefits: [
      { emoji: "📖", title: "Step-by-step", text: "Clear, illustrated instructions." },
      { emoji: "🔥", title: "Pro techniques", text: "What actually works, not theory." },
      { emoji: "💞", title: "For both", text: "Techniques for giving and receiving." },
    ],
    faqs: [{ q: "Is it beginner friendly?", a: "Yes — starts with basics and builds up." }],
  },
  {
    slug: "satisfy-your-wife",
  cover: "/covers/satisfy-your-wife.webp",
    title: "Satisfy Your Girl",
    shortTitle: "Satisfy Your Girl",
    h1: "Satisfy Your Girl",
    emoji: "💝",
    category: "Partner",
    tagline: "What she wishes you knew",
    heroSub: "The guide to understanding what she really wants — the things she wishes you knew.",
    props: ["💝 Her perspective", "🔍 What she wants", "🔥 Do it right", "💞 Deep connection"],
    rating: "4.3",
    reviewLabel: "3.1k reviews",
    pagesLabel: "50+ Pages",
    badge: "Couples' Favorite",
    price: 399,
    original: 999,
    discount: 60,
    couplesLabel: "45,000+ couples",
    pains: ["Use samajh nahi aata?", "Kya chahti hai pata nahi?", "Satisfy karna hai har baar?"],
    painNote: "Understanding her = satisfying her.",
    story: "Women's pleasure alag hota hai. Yeh guide uske perspective se batata hai — what she actually wants.",
    benefitTitle: "Her Perspective",
    benefits: [
      { emoji: "🔍", title: "What she wants", text: "Straight from women's real experiences." },
      { emoji: "🔥", title: "Do it right", text: "Techniques that hit the mark." },
      { emoji: "💞", title: "Emotional side", text: "The connection behind the pleasure." },
    ],
    faqs: [{ q: "Is this a respectful guide?", a: "Yes — it's built on consent and real communication." }],
  },
  {
    slug: "exercises-stamina-performance",
  cover: "/covers/exercises-stamina-performance.webp",
    title: "Sex Exercises: Stamina & Performance",
    shortTitle: "Sex Exercises",
    h1: "Sex Exercises: Stamina & Performance",
    emoji: "🏋️",
    category: "Wellness",
    tagline: "Simple daily moves for more control",
    heroSub: "Daily 10-minute exercises for stamina, control and confidence.",
    props: ["🏋️ 10-min daily", "⚡ More control", "🔥 Last longer", "📋 Beginner friendly"],
    rating: "4.8",
    reviewLabel: "4.2k reviews",
    pagesLabel: "35+ Pages",
    badge: "Best Value",
    price: 399,
    original: 999,
    discount: 60,
    couplesLabel: "70,000+ couples",
    pains: ["Stamina kam lagti hai?", "Control nahi hai?", "Quick fix chahiye?"],
    painNote: "10 minute daily — control and stamina build.",
    story: "Exercise se stamina and control dono improve hote hain. Yeh 10-minute daily routine hai.",
    benefitTitle: "The Daily Routine",
    benefits: [
      { emoji: "🏋️", title: "Core strength", text: "Build the muscles that matter." },
      { emoji: "⚡", title: "Stamina", text: "Last longer naturally." },
      { emoji: "🧠", title: "Control", text: "Mind-body connection for better control." },
    ],
    faqs: [{ q: "Do I need equipment?", a: "No — all exercises are bodyweight." }],
  },
  {
    slug: "sex-foods-for-stamina-power",
  cover: "/covers/sex-foods-for-stamina-power.webp",
    title: "Sex Foods for Stamina & Power",
    shortTitle: "Sex Foods",
    h1: "Sex Foods for Stamina & Power",
    emoji: "🍎",
    category: "Wellness",
    tagline: "Eat your way to better performance",
    heroSub: "The science-backed foods that boost stamina, drive and power — all Indian kitchen friendly.",
    props: ["🍎 30+ power foods", "⚡ Natural boost", "🇮🇳 Indian kitchen", "📋 Easy list"],
    rating: "4.6",
    reviewLabel: "2.2k reviews",
    pagesLabel: "40+ Pages",
    badge: "Natural Boost",
    price: 599,
    original: 999,
    discount: 40,
    couplesLabel: "25,000+ couples",
    pains: ["Supplements pe bharosa nahi?", "Natural tarika chahiye?", "Kya khaana hai pata nahi?"],
    painNote: "Natural foods — no supplements needed.",
    story: "Nature ne sab kuch diya hai. Yeh guide batata hai kaunse foods stamina aur power boost karte hain.",
    benefitTitle: "The Food List",
    benefits: [
      { emoji: "🍎", title: "30+ foods", text: "Every power food explained." },
      { emoji: "⚡", title: "How they work", text: "The science made simple." },
      { emoji: "🇮🇳", title: "Local options", text: "All available in Indian markets." },
    ],
    faqs: [{ q: "Are these foods safe daily?", a: "Yes — all are everyday Indian foods." }],
  },
  {
    slug: "100-kama-sutra-challenge",
  cover: "/covers/100-kama-sutra-challenge.jpg",
    title: "100 Kama Sutra Challenge",
    shortTitle: "Kama Sutra 100",
    h1: "The 100 Kama Sutra Challenge",
    emoji: "📜",
    category: "Positions",
    tagline: "A gamified bucket list — 100 positions, 3 levels, endless adventure",
    heroSub: "A gamified bucket list — 100 positions, 3 levels, endless adventure. By Dr. Myra Vaidya.",
    props: ["📜 100 positions", "🔥 3 levels", "🎮 Gamified", "⚡ 50% off"],
    rating: "4.5",
    reviewLabel: "1.6k reviews",
    pagesLabel: "100+ Pages",
    badge: "Gamified",
    price: 299,
    original: 599,
    discount: 50,
    couplesLabel: "55,000+ couples",
    pains: ["Kama Sutra try karna hai?", "Complete guide chahiye?", "Modern twist ke saath?"],
    painNote: "The classic — modernized for today.",
    story: "Kama Sutra ka complete collection — 100 positions, illustrated, with comfort notes and modern adaptations.",
    benefitTitle: "100 Positions",
    benefits: [
      { emoji: "📜", title: "The originals", text: "Classic positions preserved." },
      { emoji: "🔥", title: "Modern twists", text: "Updated for today's couples." },
      { emoji: "🎨", title: "Illustrated", text: "Clear visual guidance for each." },
    ],
    faqs: [{ q: "Is it respectful of the tradition?", a: "Yes — with context and respect for the original text." }],
  },
  {
    slug: "the-beast-method",
  cover: "/covers/the-beast-method.jpg",
    title: "The Beast Method",
    shortTitle: "Beast Method",
    h1: "The Beast Method — Become an Alpha",
    emoji: "🦁",
    category: "Wellness",
    tagline: "Become an Alpha",
    heroSub: "Become an Alpha. Advanced performance system by Dr. Myra Vaidya.",
    props: ["🦁 Alpha mindset", "⚡ Performance system", "🔥 40% off", "💞 Complete control"],
    rating: "4.3",
    reviewLabel: "3 reviews",
    pagesLabel: "45+ Pages",
    badge: "English",
    price: 599,
    original: 999,
    discount: 40,
    couplesLabel: "30,000+ couples",
    pains: ["Basics se aage jana hai?", "Peak performance chahiye?", "Master ban na hai?"],
    painNote: "For couples ready to master the art.",
    story: "The Beast Method is the advanced system — for those ready to take performance to the next level.",
    benefitTitle: "The System",
    benefits: [
      { emoji: "⚡", title: "Stamina system", text: "Advanced control techniques." },
      { emoji: "🔥", title: "Performance", text: "Peak every time." },
      { emoji: "💞", title: "Mastery", text: "Become unforgettable." },
    ],
    faqs: [{ q: "Is it for beginners?", a: "It's advanced — complete the basics first." }],
  },
  {
    slug: "women-mastery-ebook",
  cover: "/covers/women-mastery-ebook.webp",
    title: "Women Mastery 4 Ebooks Bundle",
    shortTitle: "Women Mastery",
    h1: "Women Mastery — 4 Ebooks Bundle",
    emoji: "👑",
    category: "Mindset",
    tagline: "Ek Bundle — complete mastery",
    heroSub: "4 ebooks ek saath — Psychology + Pleasure + Communication + Confidence. Complete mastery.",
    props: ["👑 4 ebooks", "📚 Ek bundle", "🔍 Complete mastery", "💞 Psychology + Pleasure"],
    rating: "4.5",
    reviewLabel: "2.4k reviews",
    pagesLabel: "Bundle",
    badge: "4-in-1",
    price: 599,
    original: 1199,
    discount: 50,
    couplesLabel: "35,000+ couples",
    pains: ["Poori understanding chahiye?", "Physical + emotional dono?", "Mastery ka level?"],
    painNote: "Physical and emotional — the complete picture.",
    story: "Women's pleasure is physical AND emotional. This guide covers both — the complete picture.",
    benefitTitle: "Complete Mastery",
    benefits: [
      { emoji: "🔍", title: "Understand", text: "How women's pleasure really works." },
      { emoji: "🔥", title: "Apply", text: "Techniques that deliver." },
      { emoji: "💞", title: "Connect", text: "The emotional foundation." },
    ],
    faqs: [{ q: "What makes this different?", a: "It combines emotional intelligence with physical technique." }],
  },
  {
    slug: "all-access-pass",
  cover: "/covers/all-access-pass.webp",
    title: "All Access Pass",
    shortTitle: "All Access Pass",
    h1: "All Access Pass",
    emoji: "🎟️",
    category: "Pass",
    tagline: "Every ebook, every future release",
    heroSub: "Get every ebook, course and future release with one pass. The best value for committed couples.",
    props: ["🎟️ All 16 ebooks", "🔥 Future releases", "💞 Courses included", "⚡ Instant access"],
    rating: "4.9",
    reviewLabel: "5,000+ ratings",
    pagesLabel: "Everything",
    badge: "Best Value",
    price: 1999,
    original: 8999,
    discount: 78,
    couplesLabel: "15,000+ members",
    pains: ["Har ebook alag kharidna?", "Best value chahiye?", "Sab kuch ek jagah?"],
    painNote: "One pass. Everything. Forever.",
    story: "The All Access Pass gives you every ebook, every course, and every future release — one payment, lifetime access.",
    benefitTitle: "Everything Included",
    benefits: [
      { emoji: "📚", title: "All ebooks", text: "All 16 current titles." },
      { emoji: "🔥", title: "Future releases", text: "Every new ebook free." },
      { emoji: "💞", title: "Courses", text: "Video courses included." },
    ],
    faqs: [{ q: "Is it lifetime?", a: "Yes — one payment, lifetime access to everything." }],
  },
];
